[package]
name = "gaussfit-rs"
version = "0.2.1"
edition = "2021"
description = "Rust backend for MUSE fast Gaussian fitting"
license = "MIT"
repository = "https://github.com/LM-SAL/gaussfit-rs"
readme = "README.md"

[lib]
name = "gaussfit_rs"
crate-type = ["cdylib"]

[dependencies]
num-traits = "0.2"
numpy = "0.28"
pyo3 = { version = "0.28", features = ["extension-module"] }
rayon = "1"
rmpfit = "=2.0.0"

[profile.release]
lto = true
codegen-units = 1
strip = "symbols"
